### ISSUE TITLE
Can't limit autocompletions on a per-project basis (specify feature_file_directories as a relpath?)

### ISSUE THREAD

**Issue by smoll** [austincrft/sublime-gherkin-auto-complete-plus#10]
For example, on my Mac I have a base directory where I clone all my git projects: `/Users/smoll/workspace/`

For example I might have 2 projects with `features` directories in the following locations:
`/Users/smoll/workspace/project1/features`
`/Users/smoll/workspace/project2/tests/features`

When I specify the following settings in ST3:

```
{
    // A collection of the directories containing the features files you would like to scan
    "feature_file_directories":
    [
        "/Users/smoll/workspace/**/features",
        "/Users/smoll/workspace/**/**/features",
        "/Users/smoll/workspace/**/**/**/features"
    ]
}
```

everything works, BUT when I am editing a file in `project1`, I see autocomplete suggestions from `project2`.

Anyone have any ideas how I could fix this? Might not necessarily need to change this plugin, I'm just as happy to adjust my settings/how I structure my projects on my filesystem.

**Comment by austincrft** [comment]
Ah, hadn't considered this use-case.

After a bit of research, I would suggest creating different `*.sublime-project` files for each project, and then trying to use the [ProjectSpecific](https://packagecontrol.io/packages/ProjectSpecific) ST package. Maybe this [StackOverflow question](http://stackoverflow.com/questions/10599447/is-there-any-way-to-have-project-specific-package-settings-in-sublime-text-2) will help in setting it up.

Let me know if this works out for you so I can add the steps to the README. If not, I'll see if I can come up with a better solution.

**Edit**: A more obvious solution would be for me remove the configuration file altogether and just scan the open folders in ST for `*.feature` files. My only concern with this is that the step updates will take longer for large projects.

**Comment by austincrft** [comment]
I opened #18 as an enhancement to fix this. I will leave this question open until you find a temporary solution or #18 is closed.

**Comment by smoll** [comment]
Thanks for the suggestion; I will give this a try (using the ProjectSpecific ST package) later today, and report back.

**Comment by austincrft** [comment]
Great, thanks

**Comment by Asuza** [comment]
@austincrft, I imagine you could have two modes to handle this, driven by config. The "global" mode, which you have now, allowing users to specify folders all over their system to include. And also a "project" or "local" mode that looks for "feature" folders (and then files) in the current project.

I could see someone using "global" mode for projects that share common steps, so I wouldn't drop the config that you have now. For example, if someone has a library of "Given/When/Then/etc" that they use for common tasks that they want to use in another project. In that case, they may want to read auto-complete suggestions from an existing project so that they can quickly write new feature files.

**Comment by austincrft** [comment]
I'm going to reply to this on #18.
