### ISSUE TITLE
UnicodeDecodeError and printing to console

### ISSUE THREAD

**Issue by manwinder123** [austincrft/sublime-gherkin-auto-complete-plus#27]
I am having issues parsing non-ascii characters. I have updated gherkin_parser with the following:
`file = open(file, encoding='utf-8', errors='ignore')`

I get this error with the special (unicode) character `File "/Users/manwinder/Library/Application Support/Sublime Text 3/Packages/Gherkin Auto-Complete Plus/gherkin_auto_complete_plus/utilities/gherkin_parser.py", line 52, in get_steps
    for line in file.readlines():
  File "./encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 654: ordinal not in range(128)`

If i remove the special character the plugin works.

The problem I am having is that Sublime 3 doesn't update the plugin. I have another plugin installed and when I edit its python files the sublime bar at the bottom of the GUI says the file has been updated and also in the console it says the plugin is being reloaded. When I change gherkin_parser.py none of that happens, I am unsure if this has to do with the Event Listener. Also how would I go about printing, any print statements I put into the code never seem to print, I have tried using the logger but I am unable to print anything to console.

**Comment by manwinder123** [comment]
I was able to fix the issue by completely exiting sublime and reopening it. I assume since the listener is always active that it doesn't allow for sublime to update the plugin. When I reopened it the plugin was updated.

**Comment by austincrft** [comment]
I haven't been able to find a good solution for live-reloading the package. I usually just restart ST to be safe.

I posted a comment on your PR (#28), but I will ask here because this is a better place for the discussion. Is there any reason unicode shouldn't be used? I would think that there wouldn't be any major issues because unicode also contains the ascii characters, I just wanted to verify that this will be a backwards compatible change.

**Comment by austincrft** [comment]
Fixed with #28
